name: freeclimbers_employee
description: Climbers App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+2

environment:
  sdk: '>=3.0.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  uni_links: ^0.5.1
  oktoast: ^3.3.1
  dotted_border: ^2.0.0+3
  adaptive_action_sheet:
    git:
      url: https://github.com/Majestr32/flutter_adaptive_action_sheet.git
  flutter_native_splash: ^2.2.14
  flutter_launcher_icons: ^0.11.0
  font_awesome_flutter: 9.2.0
  loading_indicator: ^3.1.0
  app_links: ^3.4.3
  loader_overlay: ^2.1.0
  webview_flutter: ^3.0.4
  image_picker: ^0.8.6
  google_fonts: ^4.0.3
  flutter_slidable:
    git:
      url: https://github.com/Majestr32/flutter_slidable_with_slide_callback.git
  onesignal_flutter: ^3.5.0
  carousel_slider: ^4.2.1
  local_auth: ^2.1.6
  universal_io: ^2.2.2
  redux_persist_flutter: ^0.9.0
  image_cropper: ^3.0.1
  flutter_wallet:
    git: https://github.com/enolcasielles/flutter_wallet.git
  freezed: ^2.2.1
  qr_code_scanner: ^1.0.1
  http_interceptor: ^2.0.0-beta.6
  path_provider: ^2.0.11
  device_display_brightness:
    git: https://github.com/ViacheslavSomin/device_display_brightness.git
  screenshot: ^2.1.0
  permission_handler: ^10.2.0
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4
  dio: ^4.0.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  dart_jsonwebtoken: ^2.4.2
  cupertino_http: ^0.0.10
  http: ^0.13.5
  super_rich_text: ^1.0.0
  url_launcher: ^6.1.10
  crypto: ^3.0.0
  intl: ^0.18.0
  qr: ^3.0.1
  connectivity_plus: ^3.0.3
  flutter_oss_licenses: ^2.0.1
  overlay_tutorial: ^3.0.0

flutter_native_splash:
  color: "#429DEB"
  color_dark: "#214C72"
  image: assets/images/logo.png
  fullscreen: true

flutter_icons:
  image_path: "assets/images/launcher_logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages